---
# Remove the _template from file name
test_data_path: "test_data_path"
data_to_process_path: "data_to_process_path"
babel_key : "babel_key"
lang: "lang"
lemma_list: [] # lemma_list
id_list: [] # id_list
tag_id_list: [] # tag_id_list
search_levels: 2 # search_levels
result_file_path: "./result.json" 
save_model_path: "./model_saved"
load_model_path: "./model_saved"